baseURL = 'https://superbro.io/'
languageCode = 'en-gb'
title = 'Superbros site'
theme = 'ananke'
publishDir = "docs"



[[params.ananke_socials]]
name = "github"
url = "https://twitter.com/suuperbro"

